/**
 * Directorio Nacional de Certificaciones de Pilates en México
 * Dataset completo de academias, escuelas formadoras y Master Trainers
 * sincronizado con docs/pilates_certification_partners_mexico_2026.csv
 */

export interface CertificationPartner {
  id: string;
  slug: string;
  partnerName: string;
  city: string;
  citySlug: string;
  state: string;
  leadPerson: string;
  roleTitle: string;
  website: string;
  email: string;
  phone: string;
  whatsapp: string;
  instagram: string;
  facebook: string;
  xTwitter?: string;
  aboutCredentials: string;
  certificationsOffered: string;
  studioLocations: string;
  partnershipFitAngle: string;
  isFlagship?: boolean;
  featuredBadges?: string[];
}

export interface CertificationCity {
  key: string; // URL slug e.g. 'cdmx', 'monterrey', etc.
  name: string; // Full name e.g. 'Ciudad de México (CDMX)'
  shortName: string; // Short name e.g. 'Ciudad de México'
  state: string; // e.g. 'CDMX', 'Nuevo León'
  landmarkImage: string; // Path to rendered landmark image
  landmarkTitle: string; // e.g. 'El Ángel de la Independencia'
  tagline: string;
  description: string;
  directorySlug?: string; // Link to studios directory if exists
  hasActiveCohort?: boolean;
  cohortLabel?: string;
}

export const CERTIFICATION_CITIES: CertificationCity[] = [
  {
    key: 'cdmx',
    name: 'Ciudad de México (CDMX)',
    shortName: 'Ciudad de México',
    state: 'CDMX',
    landmarkImage: '/images/cities/cdmx.webp',
    landmarkTitle: 'El Ángel de la Independencia',
    tagline: 'Centro neurálgico del método clásico y contemporáneo en México',
    description: 'Sede oficial de Merrithew® STOTT PILATES en Santa Fe y del linaje clásico auténtico de Romana Kryzanowska en Polanco.',
    directorySlug: 'ciudad-de-mexico',
    hasActiveCohort: true,
    cohortLabel: 'STOTT Merrithew Santa Fe',
  },
  {
    key: 'monterrey',
    name: 'Monterrey (Nuevo León)',
    shortName: 'Monterrey',
    state: 'Nuevo León',
    landmarkImage: '/images/cities/monterrey.webp',
    landmarkTitle: 'Cerro de la Silla & San Pedro',
    tagline: 'Epicentro boutique y formación de alto nivel en San Pedro Garza García',
    description: 'Convocatoria oficial para la Cohorte CAMA (Dic 2026 – Ene 2027) con Gabi y Laura Munive, junto a las principales academias del norte del país.',
    directorySlug: 'monterrey',
    hasActiveCohort: true,
    cohortLabel: 'Cohorte Oficial Dic 2026',
  },
  {
    key: 'queretaro',
    name: 'Querétaro (Querétaro)',
    shortName: 'Querétaro',
    state: 'Querétaro',
    landmarkImage: '/images/cities/queretaro.webp',
    landmarkTitle: 'Los Arcos de Querétaro',
    tagline: 'Formación clásica y avales con valor curricular oficial SEP en el Bajío',
    description: 'Cohorte presencial CAMA (Nov 2026) en Álamos y Corregidora, combinando avales oficiales SEP-CONOCER y tradición de Power Pilates NYC.',
    directorySlug: 'queretaro',
    hasActiveCohort: true,
    cohortLabel: 'Cohorte Oficial Nov 2026',
  },
  {
    key: 'guadalajara',
    name: 'Guadalajara (Jalisco)',
    shortName: 'Guadalajara / Zapopan',
    state: 'Jalisco',
    landmarkImage: '/images/cities/guadalajara.webp',
    landmarkTitle: 'Catedral de Guadalajara',
    tagline: 'Linaje clásico directo de 4ª generación y boutiques de hiper-lujo',
    description: 'Escuelas clásicas formadas bajo la tutela de Elena Bartley y Real Pilates NYC en Zapopan y Guadalajara.',
    directorySlug: 'guadalajara',
    hasActiveCohort: false,
  },
  {
    key: 'puebla',
    name: 'Puebla (Puebla)',
    shortName: 'Puebla',
    state: 'Puebla',
    landmarkImage: '/images/cities/puebla.webp',
    landmarkTitle: 'Santuario de Cholula & Popocatépetl',
    tagline: 'Tradición clásica pionera y enfoque clínico biomecánico',
    description: 'Más de 25 años formando maestras en Angelópolis y Cholula con certificaciones NPCP y especialidad en columna y rehabilitación.',
    directorySlug: 'puebla',
    hasActiveCohort: false,
  },
  {
    key: 'puerto-vallarta',
    name: 'Puerto Vallarta (Jalisco)',
    shortName: 'Puerto Vallarta',
    state: 'Jalisco',
    landmarkImage: '/images/cities/puerto-vallarta.webp',
    landmarkTitle: 'Los Arcos del Malecón',
    tagline: 'Retiros de formación integral y bienestar en la costa del Pacífico',
    description: 'Formaciones comprensivas de 250 horas preparando para el examen profesional NPCP, combinando biomecánica y turismo de bienestar.',
    hasActiveCohort: false,
  },
  {
    key: 'tijuana',
    name: 'Tijuana (Baja California)',
    shortName: 'Tijuana',
    state: 'Baja California',
    landmarkImage: '/images/cities/tijuana.webp',
    landmarkTitle: 'Reloj Monumental de Av. Revolución',
    tagline: 'Formación binacional de alto poder adquisitivo Tijuana – San Diego',
    description: 'Cursos intensivos en Zona Río y Playas con validez binacional México – EE.UU. bajo estándares ITTAP y PMA.',
    hasActiveCohort: false,
  },
  {
    key: 'riviera-maya',
    name: 'Riviera Maya (Cancún / Playa del Carmen)',
    shortName: 'Riviera Maya',
    state: 'Quintana Roo',
    landmarkImage: '/images/cities/riviera-maya.webp',
    landmarkTitle: 'Costa Maya & Mar Caribe Turquesa',
    tagline: 'Certificaciones internacionales para resorts, spas y estudios boutique',
    description: 'Formación en todo el sistema Pilates con linaje Romana Kryzanowska y acreditación NPCP en el principal destino turístico del Caribe.',
    hasActiveCohort: false,
  },
  {
    key: 'leon',
    name: 'León (Guanajuato)',
    shortName: 'León',
    state: 'Guanajuato',
    landmarkImage: '/images/cities/leon.webp',
    landmarkTitle: 'Templo Expiatorio del Santísimo Sacramento',
    tagline: 'Máxima exigencia clásica y vínculo con medicina del deporte en el Bajío',
    description: 'Formación presencial directa de Inelia Garcia (+550h de práctica en aparatos) en Foro 4 León y diplomados en biomecánica funcional.',
    hasActiveCohort: false,
  },
  {
    key: 'merida',
    name: 'Mérida (Yucatán)',
    shortName: 'Mérida',
    state: 'Yucatán',
    landmarkImage: '/images/cities/merida.webp',
    landmarkTitle: 'Monumento a la Patria en Paseo de Montejo',
    tagline: 'Sede oficial de The New York Pilates Studio Teacher Training',
    description: 'El referente clásico del sureste mexicano impartido con el aval directo de Sean Gallagher en estudios equipados con aparatos de precisión.',
    hasActiveCohort: false,
  },
];

export const CERTIFICATION_PARTNERS: CertificationPartner[] = [
  // PUEBLA
  {
    id: 'sense-pilates-puebla',
    slug: 'sense-pilates',
    partnerName: 'Sense Pilates Studio',
    city: 'Puebla',
    citySlug: 'puebla',
    state: 'Puebla',
    leadPerson: 'Olga Estrada',
    roleTitle: 'Fundadora & Master Trainer (NPCP #36456)',
    website: 'https://www.sensepilates.com.mx',
    email: 'contacto@sensepilates.com.mx',
    phone: '+52 222 426 8686',
    whatsapp: '+522224268686',
    instagram: 'https://www.instagram.com/sensepilates/',
    facebook: 'https://www.facebook.com/sensepilates',
    aboutCredentials: 'Lic. en Comunicación (UDLAP 2002), 22+ años de experiencia docente. Certificada internacionalmente por NPCP (#36456), JL Body Conditioning y Patricia Martínez. Dos maestrías y especialidad clínica en columna vertebral, escoliosis y rehabilitación postural.',
    certificationsOffered: 'Certificación Reformer & Mat Clásico (55h presenciales en Cholula/Puebla: Básico, Intermedio y Avanzado con implementos y biomecánica funcional).',
    studioLocations: 'Calzada Zavaleta #2316 Local 12 (Plaza Rincón de Zavaleta) y San Pedro Cholula, Puebla.',
    partnershipFitAngle: 'Sede aliada AAA en Puebla. Alta demanda de camas reformer profesionales de madera de roble para graduadas que abren estudios boutique en Angelópolis y Cholula.',
    featuredBadges: ['NPCP #36456', '55h Reformer & Mat', 'Especialidad Columna'],
  },
  {
    id: 'patty-martinez-pilates-puebla',
    slug: 'patty-martinez-pilates',
    partnerName: 'Pilates Studio by Patty Martínez',
    city: 'Puebla',
    citySlug: 'puebla',
    state: 'Puebla',
    leadPerson: 'Patricia Martínez',
    roleTitle: 'Directora & Pionera Educadora',
    website: 'https://www.facebook.com/pilatesstudiopatriciamartinez',
    email: 'patty_p@hotmail.com',
    phone: '+52 222 261 0550',
    whatsapp: '+522222610550',
    instagram: 'https://www.instagram.com/pilatesstudiopatriciamartinez/',
    facebook: 'https://www.facebook.com/pilatesstudiopatriciamartinez',
    aboutCredentials: 'Pionera indiscutible de la enseñanza de Pilates Clásico en Puebla y Cholula con más de 25 años de trayectoria ininterrumpida. Formadora histórica de múltiples generaciones de maestras de prestigio en el centro del país.',
    certificationsOffered: 'Formación integral en Reformer, Mat, Cadillac y Silla Wunda bajo la rigurosa escuela clásica JL Body Conditioning.',
    studioLocations: 'Av. 12 Poniente 501-G, San Pedro Cholula, Puebla C.P. 72760.',
    partnershipFitAngle: 'Máxima autoridad histórica en Puebla. Alianza de prestigio y canal de recomendación para equipamiento premium de madera y alta durabilidad.',
    featuredBadges: ['25+ Años Trayectoria', 'JL Body Conditioning', 'Sistema Completo'],
  },
  {
    id: 'zolo-pilates-puebla',
    slug: 'zolo-pilates',
    partnerName: 'Zolo Pilates',
    city: 'Puebla',
    citySlug: 'puebla',
    state: 'Puebla / Morelos',
    leadPerson: 'MariCarmen Talayero González',
    roleTitle: 'Directora de Formación & NCPT Master Teacher',
    website: 'https://www.zolopilates.com',
    email: 'zolopilates@hotmail.com',
    phone: '+52 777 476 0075',
    whatsapp: '+527774760075',
    instagram: 'https://www.instagram.com/zolopilates/',
    facebook: 'https://www.facebook.com/zolopilates',
    aboutCredentials: 'Diseñadora industrial de origen reconvertida en Master Teacher desde 2008. Certificada NCPT ante el National Pilates Certification Program. Especialista en biomecánica, control motor y diseño ergonómico del movimiento.',
    certificationsOffered: 'Diplomado Integral para Maestros de Pilates (Reformer, Mat, Implementos) avalado internacionalmente con talleres intensivos itinerantes.',
    studioLocations: 'Corredor Puebla – Cuernavaca con talleres y masterclasses presenciales.',
    partnershipFitAngle: 'Perfil de diseño industrial que aprecia la manufactura de precisión de las camas CAMA (madera de roble/maple, herrajes de acero inoxidable y rieles silenciosos).',
    featuredBadges: ['NCPT Certified', 'Control Motor', 'Diseño Ergonómico'],
  },

  // MONTERREY
  {
    id: 'fmp-monterrey',
    slug: 'formacion-maestros-pilates',
    partnerName: 'Formación de Maestros de Pilates (FMP)',
    city: 'Monterrey',
    citySlug: 'monterrey',
    state: 'Nuevo León',
    leadPerson: 'Sabina Jiménez Colín',
    roleTitle: 'Maestra Formadora Internacional (NPCP ID 782676)',
    website: 'https://formaciondemaestrosdepilates.com',
    email: 'contacto@formaciondemaestrosdepilates.com',
    phone: '+52 55 1830 0099',
    whatsapp: '+525518300099',
    instagram: 'https://www.instagram.com/fmpilates/',
    facebook: 'https://www.facebook.com/formaciondemaestrosdepilates',
    aboutCredentials: 'Inició en Pilates en 2006. Certificada National Certified Pilates Teacher (NCPT #782676) por la NPCP de EE.UU. Imparte cursos oficiales de educación continua CEC avalados por la NPCP y reconocidos a nivel continental.',
    certificationsOffered: 'Cursos intensivos en Monterrey de Cadillac/Torre, Rutina Clásica de Reformer y Matwork (Diplomas con créditos CEC internacionales).',
    studioLocations: 'Sedes rotativas en San Pedro Garza García y Monterrey Centro.',
    partnershipFitAngle: 'Aliada estratégica directa para las cohortes de certificación de CAMA en Monterrey (Diciembre 2026 – Enero 2027) y co-docente invitada en masterclasses.',
    featuredBadges: ['NPCP ID 782676', 'Créditos CEC EE.UU.', 'Clásico & Contemporáneo'],
    isFlagship: true,
  },
  {
    id: 'v-pilates-monterrey',
    slug: 'v-pilates-studio',
    partnerName: 'V Pilates Studio',
    city: 'Monterrey',
    citySlug: 'monterrey',
    state: 'Nuevo León',
    leadPerson: 'Vero Garza',
    roleTitle: 'Fundadora & Master Coach',
    website: 'https://www.facebook.com/vpilatesmx',
    email: 'vpilatesmx@gmail.com',
    phone: '+52 81 8472 9003',
    whatsapp: '+528184729003',
    instagram: 'https://www.instagram.com/vpilatesmx/',
    facebook: 'https://www.facebook.com/vpilatesmx',
    aboutCredentials: 'Más de 35 años de trayectoria en acondicionamiento físico, danza y Pilates. Referente absoluta en el corredor de alta plusvalía de San Pedro Garza García y Valle Oriente con cientos de alumnas formadas.',
    certificationsOffered: 'Certificación de Pilates Mat + Accesorios y Reformer con acreditación internacional y enfoque terapéutico-rehabilitativo.',
    studioLocations: 'Av. Fundadores 955, Plaza Sienna Local 14 (2do piso), Valle Oriente, Monterrey C.P. 64753.',
    partnershipFitAngle: 'Estudio premium en San Pedro / Valle Oriente; ideal como showroom físico y embajadora de la marca para ventas B2B de reformers en Nuevo León.',
    featuredBadges: ['35+ Años Experiencia', 'San Pedro Garza García', 'Enfoque Terapéutico'],
  },
  {
    id: 'alves-pilates-monterrey',
    slug: 'alves-pilates-monterrey',
    partnerName: 'Alves Pilates Monterrey',
    city: 'Monterrey',
    citySlug: 'monterrey',
    state: 'Nuevo León',
    leadPerson: 'Metztli Palomino / Sandro Alves',
    roleTitle: 'Coordinadora de Formación Norte / Director de Red',
    website: 'https://www.alvespilates.com.mx',
    email: 'cursos@alvespilates.com',
    phone: '+52 55 8568 0905',
    whatsapp: '+525585680905',
    instagram: 'https://www.instagram.com/alvespilatesmexico/',
    facebook: 'https://www.facebook.com/alvespilatesoficial',
    aboutCredentials: 'Alves Pilates es la red de formación más grande de Sudamérica con presencia en 10 países. Metztli Palomino es Master Trainer y formadora de 3ª generación directa de Joseph Pilates.',
    certificationsOffered: 'Programa Integral de 115h (Nacional) a 452h (Internacional de 3ª generación con horas válidas para presentar el examen PMA/NPCP). Módulos presenciales en Monterrey.',
    studioLocations: 'Sede Monterrey (San Pedro / Cumbres).',
    partnershipFitAngle: 'Volumen masivo de alumnos que requieren adquirir camas de pilates para graduarse o emprender sus propios estudios en el norte de México.',
    featuredBadges: ['Red en 10 Países', '115h a 452h Integral', '3ª Generación Directa'],
  },
  {
    id: 'catalina-colin-monterrey',
    slug: 'catalina-colin-pilates',
    partnerName: 'Catalina Colín Pilates (Cohortes MTY)',
    city: 'Monterrey',
    citySlug: 'monterrey',
    state: 'Nuevo León',
    leadPerson: 'Catalina Colín',
    roleTitle: 'Directora ITTAP & Formadora Nacional',
    website: 'https://catalinacolin.com',
    email: 'pilatesformacion@catalinacolin.com',
    phone: '+52 55 1830 0099',
    whatsapp: '+525518300099',
    instagram: 'https://www.instagram.com/catalina_c_h/',
    facebook: 'https://www.facebook.com/catalinacolinpilates',
    aboutCredentials: 'Fundadora del prestigioso programa ITTAP (Instructor Training Program). Ha formado a cientos de instructores en Monterrey, CDMX y el Bajío. Reconocida por estándares de la PMA y NPCP.',
    certificationsOffered: 'Curso Intensivo de Certificación Pilates Reformer 30 Horas con práctica intensiva, biomecánica y repertorio clásico/contemporáneo.',
    studioLocations: 'Eventos y cohortes presenciales en San Pedro Garza García y Monterrey.',
    partnershipFitAngle: 'Vende paquetes de formación + cama. Potencial alianza de distribución mayorista de camas CAMA para sus estudiantes que inician estudio.',
    featuredBadges: ['ITTAP Founder', 'Reformer Intensivo 30h', 'PMA / NPCP Standards'],
  },

  // QUERÉTARO
  {
    id: 'at-studio-queretaro',
    slug: 'at-studio-pilates-academy',
    partnerName: 'AT STUDIO Pilates Academy',
    city: 'Querétaro',
    citySlug: 'queretaro',
    state: 'Querétaro',
    leadPerson: 'Ángeles Trabas Toro',
    roleTitle: 'Directora General, Fundadora & Docente Internacional',
    website: 'https://www.atstudio.com.mx',
    email: 'contacto@atstudiopilates.academy',
    phone: '+52 56 1607 0912',
    whatsapp: '+525616070912',
    instagram: 'https://www.instagram.com/atstudio_pilates_academy/',
    facebook: 'https://www.facebook.com/atstudiopilates',
    aboutCredentials: 'Nacida en Madrid, España. Más de 15 años de trayectoria en danza, fitness y rehabilitación física. Formada en Pilates Clásico (Madrid), Stott Reformer, Redcord Active (NY), PNL y Coaching. Certificaciones con RVOE / Cédula técnica SEP-CONOCER y respaldo UNACH.',
    certificationsOffered: 'Certificaciones Presenciales y Online en Pilates Reformer, Mat, Barre, Poblaciones Especiales y Terapéutico con valor curricular oficial SEP.',
    studioLocations: 'Prolongación Paseo de Amsterdam 481, Los Olvera / Corregidora, Querétaro C.P. 76904.',
    partnershipFitAngle: 'Clave para otorgar aval académico oficial SEP-CONOCER y RVOE a graduadas de la región del Bajío. Alianza institucional inigualable.',
    featuredBadges: ['Aval SEP-CONOCER', 'Respaldo UNACH', 'Clásico & Stott Formada'],
    isFlagship: true,
  },
  {
    id: 'studio-c-queretaro',
    slug: 'studio-c-pilates-clasico',
    partnerName: 'Studio C Pilates Clásico',
    city: 'Querétaro',
    citySlug: 'queretaro',
    state: 'Querétaro',
    leadPerson: 'Charissa (Charis) Salazar Arriaga',
    roleTitle: 'Studio Director & Power Pilates Certified Instructor',
    website: 'https://studiocpilates.mx',
    email: 'studiocpilates@yahoo.com',
    phone: '+52 442 155 9664',
    whatsapp: '+524421559664',
    instagram: 'https://www.instagram.com/studiocpilatesclasico/',
    facebook: 'https://www.facebook.com/studiocpilatesclasico',
    aboutCredentials: 'Certificada por Power Pilates (la prestigiosa escuela clásica de Nueva York) con más de 12 años dirigiendo el estudio clásico de referencia indiscutible en Querétaro.',
    certificationsOffered: 'Mentorías privadas, talleres técnicos para instructores y formación continua en aparatos clásicos (Reformer, Cadillac, Wunda Chair).',
    studioLocations: 'Calle Manufactura 8 Bis, Fraccionamiento Álamos 2da Sección, Querétaro, Qro. 76160.',
    partnershipFitAngle: 'Ubicación céntrica y de prestigio en Álamos; sede ideal de práctica supervisada en la cohorte presencial de Querétaro.',
    featuredBadges: ['Power Pilates New York', 'Álamos 2da Sección', 'Aparatos Clásicos'],
  },
  {
    id: 'suit-pilates-queretaro',
    slug: 'suit-pilates-studio',
    partnerName: 'Suit Pilates Studio Qro',
    city: 'Querétaro',
    citySlug: 'queretaro',
    state: 'Querétaro',
    leadPerson: 'Carmen Sandoval',
    roleTitle: 'Fundadora & Instructora Principal',
    website: 'https://www.instagram.com/suitpilates_studio_qro_mx/',
    email: 'suitpilates@gmail.com',
    phone: '+52 442 204 9155',
    whatsapp: '+524422049155',
    instagram: 'https://www.instagram.com/suitpilates_studio_qro_mx/',
    facebook: 'https://www.facebook.com/suitpilates',
    aboutCredentials: 'Especialista en entrenamiento dinámico sobre aparatos, acondicionamiento físico funcional y biomecánica postural con más de 10 años de práctica docente en el Bajío.',
    certificationsOffered: 'Talleres formativos y módulos de perfeccionamiento en Reformer, Matwork, Tower y Esfero Pilates.',
    studioLocations: 'Plaza San Andrés, Av. Universidad 131, Centro Histórico, Querétaro C.P. 76000.',
    partnershipFitAngle: 'Fuerte tracción comunitaria en el Centro de Querétaro y captación constante de alumnas universitarias y jóvenes profesionales.',
    featuredBadges: ['Centro Histórico', 'Biomecánica Postural', 'Reformer & Tower'],
  },

  // CIUDAD DE MÉXICO (CDMX)
  {
    id: 'the-pilates-school-cdmx',
    slug: 'the-pilates-school-roma',
    partnerName: 'The Pilates School / Mindbody',
    city: 'Ciudad de México',
    citySlug: 'cdmx',
    state: 'CDMX',
    leadPerson: 'Venecia Hernández',
    roleTitle: 'CEO, Fundadora & NCPT #12456',
    website: 'https://www.thepilatesschool.mx',
    email: 'info@pilatesschool.com',
    phone: '+52 55 7321 6082',
    whatsapp: '+525573216082',
    instagram: 'https://www.instagram.com/thepilatesschool.mx/',
    facebook: 'https://www.facebook.com/thepilatesschoolmx',
    aboutCredentials: 'Más de 14 años de experiencia docente, certificada NCPT (#12456). Ha formado a más de 15,000 alumnos en Mindbody Pilates Studio bajo una metodología pedagógica basada en evidencia científica y rigor anatómico.',
    certificationsOffered: 'Certificación Reformer (214h), Mat (118h) y Certificación Comprensiva Completa (332h) con preparación directa para el examen internacional de la NPCP.',
    studioLocations: 'Tabasco 152, Colonia Roma Norte, Cuauhtémoc, CDMX C.P. 06700.',
    partnershipFitAngle: 'La academia más estructurada y moderna de la Roma Norte. Sus graduadas abren estudios independientes continuamente y requieren proveedores locales de reformers de alta gama.',
    featuredBadges: ['NCPT #12456', '214h a 332h Horas Avaladas', 'Roma Norte'],
    isFlagship: true,
  },
  {
    id: 'authentic-pilates-cdmx',
    slug: 'authentic-pilates-mexico',
    partnerName: 'Authentic Pilates México',
    city: 'Ciudad de México',
    citySlug: 'cdmx',
    state: 'CDMX',
    leadPerson: 'Nora García',
    roleTitle: 'Directora & Única Maestra de 2da Generación en México',
    website: 'https://authenticpilatesmexico.com',
    email: 'certificacion@authenticpilatesmexico.com',
    phone: '+52 55 5281 0239',
    whatsapp: '+525565372726',
    instagram: 'https://www.instagram.com/authenticpilatesmexico/',
    facebook: 'https://www.facebook.com/authenticpilatesmexico',
    aboutCredentials: 'Única profesora de 2ª generación en México, formada y certificada directamente por Romana Kryzanowska (discípula directa elegida por Joseph Pilates). Más de 20 años de enseñanza inquebrantable del método clásico original.',
    certificationsOffered: 'Exclusivo programa de certificación de 9 meses con más de 600 horas de aprendizaje clásico integral en aparatos originales.',
    studioLocations: 'Campos Elíseos / Tennyson, Polanco, Miguel Hidalgo, CDMX.',
    partnershipFitAngle: 'El pináculo del linaje clásico en América Latina. Alianza de máxima credibilidad para posicionar la línea de camas de madera noble (roble y nogal).',
    featuredBadges: ['2ª Gen Romana Kryzanowska', '+600h Programa Élite', 'Polanco Clásico'],
    isFlagship: true,
  },
  {
    id: 'the-fit-academy-cdmx',
    slug: 'the-fit-academy',
    partnerName: 'The Fit Academy',
    city: 'Ciudad de México',
    citySlug: 'cdmx',
    state: 'CDMX',
    leadPerson: 'Comité Directivo & Master Trainers',
    roleTitle: 'Directores Académicos (Aval SEP-CONOCER / ISSA)',
    website: 'https://fitpilates.mx/academy/',
    email: 'academy@fitpilates.mx',
    phone: '+52 55 4500 1234',
    whatsapp: '+525545001234',
    instagram: 'https://www.instagram.com/thefitpilates/',
    facebook: 'https://www.facebook.com/thefitpilatesmx',
    aboutCredentials: 'Academia formativa de alto volumen comercial con más de 200 egresados activos. Programas avalados por SEP-CONOCER (Estándar 0217) e ISSA (International Sports Sciences Association).',
    certificationsOffered: 'Formaciones profesionales modulares en MAT, REFORMER, SPRINGBOARD y CHAIR con esquemas de financiamiento a meses sin intereses.',
    studioLocations: 'Sucursales en Condesa, Del Valle y Santa Fe.',
    partnershipFitAngle: 'Alianza de volumen para proveer camas de aluminio anodizado y reformer con media torre a los estudios que abren sus egresados.',
    featuredBadges: ['SEP Estándar 0217', 'Aval ISSA', 'Condesa / Del Valle / Santa Fe'],
  },
  {
    id: 'pilates-educare-stott-cdmx',
    slug: 'pilates-educare-stott-cdmx',
    partnerName: 'Pilates EduCare / Es.sence (Host Oficial STOTT Merrithew®)',
    city: 'Ciudad de México',
    citySlug: 'cdmx',
    state: 'CDMX',
    leadPerson: 'Lead Instructor Trainers STOTT',
    roleTitle: 'Centro de Entrenamiento con Licencia Oficial Merrithew®',
    website: 'https://camadepilates.com/certificacion-pilates/cdmx',
    email: 'contacto@pilateseducare.com',
    phone: '+52 55 4846 8190',
    whatsapp: '+525548468190',
    instagram: 'https://www.instagram.com/pilateseducare/',
    facebook: 'https://www.facebook.com/pilateseducare',
    aboutCredentials: 'Sede de entrenamiento con licencia oficial de Merrithew® en Santa Fe. La certificación STOTT PILATES® es reconocida internacionalmente como el "Gold Standard" en más de 100 países.',
    certificationsOffered: 'Intensive Reformer (IR - 125h), Intensive Mat-Plus™ (IMP), Cadillac, Chair & Barrels con opción a examen de certificación internacional.',
    studioLocations: 'Prolongación Paseo de la Reforma, Santa Fe, Álvaro Obregón, CDMX.',
    partnershipFitAngle: 'Sede de certificación promovida activamente en camadepilates.com/certificacion-pilates/cdmx. Canal directo de venta de accesorios y camas complementarias.',
    featuredBadges: ['Gold Standard Merrithew®', '125h Intensive Reformer', 'Validez en 100+ Países'],
    isFlagship: true,
  },

  // GUADALAJARA / ZAPOPAN
  {
    id: 'pilates-clasico-gdl',
    slug: 'pilates-clasico-guadalajara',
    partnerName: 'Pilates Clásico GDL (Certificación México)',
    city: 'Guadalajara',
    citySlug: 'guadalajara',
    state: 'Jalisco',
    leadPerson: 'Mara Adame',
    roleTitle: 'Directora & Maestra de 4ta Generación',
    website: 'https://certificacionpilates.com/certificacion-pilates-clasico',
    email: 'info@pilatesclasico.com',
    phone: '+52 33 2155 0201',
    whatsapp: '+523321550201',
    instagram: 'https://www.instagram.com/adame_mara/',
    facebook: 'https://www.facebook.com/pilatesclasicogdl',
    aboutCredentials: 'Alumna directa de Elena Bartley (2da generación de Romana Kryzanowska). Certificada por el Pilates Center of Las Vegas. Con más de 12 años formando instructores en todo el occidente de México.',
    certificationsOffered: 'Certificación de Pilates Clásico en 4 Módulos: Sistema completo en Mat, Reformer, Silla Wunda, Cadillac, Corrector de Espina y preparación NPCP.',
    studioLocations: 'Plaza Epicentra Local 203, Carr. Guadalajara-Tepic 7355, Col. San Juan de Ocotán, Zapopan, Jal. C.P. 45019.',
    partnershipFitAngle: 'Principal formadora clásica del occidente del país; excelente sinergia para paquetes conjuntos de formación y camas profesionales de estudio.',
    featuredBadges: ['4ª Gen Directa', 'Zapopan Epicentra', 'Sistema Completo 4 Módulos'],
    isFlagship: true,
  },
  {
    id: 'icon-pilates-gdl',
    slug: 'icon-pilates-studio',
    partnerName: 'Icon Pilates Studio',
    city: 'Guadalajara',
    citySlug: 'guadalajara',
    state: 'Jalisco',
    leadPerson: 'Alina Durán Roux',
    roleTitle: 'Fundadora & Real Pilates NY Teacher Trainer',
    website: 'https://www.iconpilates.com',
    email: 'contacto@iconpilates.com',
    phone: '+52 33 1149 1945',
    whatsapp: '+523311491945',
    instagram: 'https://www.instagram.com/iconpilates/',
    facebook: 'https://www.facebook.com/iconpilatesgdl',
    aboutCredentials: 'Ex-triatleta internacional, licenciada en diseño en Florencia (Italia), graduada del prestigioso Real Pilates Teacher Training Program de Alycea Ungaro (NYC 2016) y Pilates Center of Las Vegas. Ex-entrenadora en Cirque du Soleil.',
    certificationsOffered: 'Host oficial del Real Pilates Teacher Training (Nueva York) en México; mentorías individuales y talleres avanzados de aparato clásico.',
    studioLocations: 'Santa Teresa de Jesús #34, Col. Camino Real, Zapopan / Guadalajara, Jal.',
    partnershipFitAngle: 'Boutique de hiper-lujo con enorme influencia visual en Guadalajara; embajadora de marca ideal para las líneas de roble, nogal y cuero.',
    featuredBadges: ['Real Pilates New York', 'Cirque du Soleil Trainer', 'Zapopan Camino Real'],
  },

  // PUERTO VALLARTA
  {
    id: 'nacer-pilates-vallarta',
    slug: 'nacer-estudio-pilates',
    partnerName: 'NACER Estudio Pilates y Yoga',
    city: 'Puerto Vallarta',
    citySlug: 'puerto-vallarta',
    state: 'Jalisco',
    leadPerson: 'Luz Teresa (Tere) López',
    roleTitle: 'Fundadora, Master Teacher NPCP & Pilates 4 Parkinson\'s',
    website: 'https://nacerpilatesyoga.com',
    email: 'vuelve@nacerpilatesyoga.com',
    phone: '+52 322 232 1142',
    whatsapp: '+523222321142',
    instagram: 'https://www.instagram.com/nacerpilatesyoga/',
    facebook: 'https://www.facebook.com/nacerestudio',
    aboutCredentials: 'Más de 23 años de trayectoria en el método clásico y terapéutico. Maestra certificada NPCP ante la National Pilates Certification Program. Especializada en biomecánica para adultos mayores y patologías neurológicas.',
    certificationsOffered: 'Formación de Maestros de Pilates en 5 Módulos presenciales (250 horas totales) en Puerto Vallarta, preparando para el examen profesional NPCP.',
    studioLocations: 'Plaza Península Local C20, Av. Francisco Medina Asencio #2485, Zona Hotelera Norte, Puerto Vallarta C.P. 48333.',
    partnershipFitAngle: 'Punto neurálgico de retiros y turismo de certificación en la costa del Pacífico; oportunidad clave de equipar villas privadas y hoteles boutique.',
    featuredBadges: ['NPCP Certified', '250h en 5 Módulos', 'Plaza Península Vallarta'],
    isFlagship: true,
  },

  // TIJUANA / BAJA
  {
    id: 'ittap-tijuana',
    slug: 'ittap-formacion-pilates-baja',
    partnerName: 'ITTAP / Formación Pilates Baja',
    city: 'Tijuana',
    citySlug: 'tijuana',
    state: 'Baja California',
    leadPerson: 'Catalina Colín & Red Regional',
    roleTitle: 'Master Trainer ITTAP',
    website: 'https://catalinacolin.com/cursos_y_formacion_de_pilates_mexico/',
    email: 'pilatesformacion@catalinacolin.com',
    phone: '+52 55 1830 0099',
    whatsapp: '+525518300099',
    instagram: 'https://www.instagram.com/catalina_c_h/',
    facebook: 'https://www.facebook.com/catalinacolinpilates',
    aboutCredentials: 'Programas recurrentes anuales en Tijuana y Mexicali con respaldo ITTAP / PMA para certificar instructoras binacionales que imparten clases en Tijuana y el sur de California (San Diego).',
    certificationsOffered: 'Certificación Pilates Reformer 30 Horas y Curso Pilates Mat intensivo de fin de semana con enfoque de aplicación inmediata.',
    studioLocations: 'Zona Río y Playas de Tijuana, Baja California.',
    partnershipFitAngle: 'Mercado binacional con cobro en USD ($40-$65 USD la clase). Alumnas con alto poder adquisitivo para equipar sus estudios privados en la frontera norte.',
    featuredBadges: ['Mercado Binacional San Diego', 'Reformer Intensivo 30h', 'Zona Río Tijuana'],
    isFlagship: true,
  },

  // RIVIERA MAYA (CANCÚN / PLAYA DEL CARMEN)
  {
    id: 'escuela-pilates-riviera-maya',
    slug: 'escuela-de-pilates-mexico-muv',
    partnerName: 'Escuela de Pilates México / MUV Studio',
    city: 'Riviera Maya',
    citySlug: 'riviera-maya',
    state: 'Quintana Roo',
    leadPerson: 'Alejandra Macías',
    roleTitle: 'Directora General & NCPT #43062',
    website: 'https://www.escueladepilates.mx',
    email: 'contacto@escueladepilates.mx',
    phone: '+52 981 133 3807',
    whatsapp: '+529811333807',
    instagram: 'https://www.instagram.com/escueladepilatesmx/',
    facebook: 'https://www.facebook.com/escueladepilatesmx',
    aboutCredentials: 'Lic. en Administración con posgrado en Ciencias de la Educación (Universidad Anáhuac). Certificada internacionalmente NPCP (#43062) en Mat y Sistema Completo. Más de 13 años de experiencia y linaje directo de Romana Kryzanowska.',
    certificationsOffered: 'Formación Comprensiva en Todo el Sistema Pilates (Mat, Reformer, Wunda Chair, Tower) con mentorías personalizadas presenciales en Cancún y Playa del Carmen.',
    studioLocations: 'Presencial en Cancún, Playa del Carmen y Campeche; campus virtual para todo México.',
    partnershipFitAngle: 'Gran influencia en el Caribe Mexicano; canal estratégico para equipar resorts de lujo, spas de bienestar y estudios para nómadas digitales.',
    featuredBadges: ['NCPT #43062', 'Cancún & Playa del Carmen', 'Sistema Completo Romana'],
    isFlagship: true,
  },

  // LEÓN
  {
    id: 'autentico-pilates-leon',
    slug: 'autentico-pilates-inelia-garcia-leon',
    partnerName: 'Certificación Auténtico Pilates México (Turma Inelia Garcia)',
    city: 'León',
    citySlug: 'leon',
    state: 'Guanajuato',
    leadPerson: 'Inelia Garcia & Daniela Pérez Salinas',
    roleTitle: 'Master Teacher of Teachers & Directora Sede León',
    website: 'https://certificacionautenticopilates.mx/',
    email: 'contacto@certificacionautenticopilates.mx',
    phone: '+52 477 330 4444',
    whatsapp: '+524773304444',
    instagram: 'https://www.instagram.com/autenticopilatesmexico/',
    facebook: 'https://www.facebook.com/autenticopilatesmexico',
    aboutCredentials: 'Inelia Garcia fue nombrada Teacher of Teachers por Romana Kryzanowska. Daniela Pérez coordina la sede en Foro 4 León. Formación presencial de élite en todo el sistema clásico con más de 550 horas de práctica en aparatos originales.',
    certificationsOffered: 'Certificación Integral Auténtico Pilates (Básico, Intermedio, Avanzado en Reformer, Cadillac, Wunda Chair, Electric Chair, Spine Corrector).',
    studioLocations: 'Foro 4 León, Manuel J. Clouthier 304, Jardines del Campestre, 37128 León, Gto.',
    partnershipFitAngle: 'Máximo linaje clásico en el Bajío con alta demanda de equipamiento de madera de roble/nogal de alta fidelidad biomecánica para sus egresados.',
    featuredBadges: ['Linaje Inelia Garcia', '+550h Práctica Clásica', 'Foro 4 Campestre León'],
    isFlagship: true,
  },
  {
    id: 'educasport-leon',
    slug: 'educasport-pilates-evolution',
    partnerName: 'Educasport / Pilates Evolution Bajío',
    city: 'León',
    citySlug: 'leon',
    state: 'Guanajuato',
    leadPerson: 'Coordinación Académica Educasport',
    roleTitle: 'Dirección Técnica de Certificaciones Deportivas',
    website: 'https://www.educacont.mx/educasport/Certificacion-Pilates-Evolution',
    email: 'contacto@educacont.mx',
    phone: '+52 477 717 0000',
    whatsapp: '+524777170000',
    instagram: 'https://www.instagram.com/educasportmexico/',
    facebook: 'https://www.facebook.com/educasportmexico',
    aboutCredentials: 'Organización especializada en formación continua en ciencias del deporte, biomecánica y control motor para fisioterapeutas y preparadores físicos.',
    certificationsOffered: 'Certificación Pilates Evolution: Biomecánica funcional, Matwork Avanzado e Implementos / Aparatología en Reformer.',
    studioLocations: 'León, Guanajuato y conexión con el corredor industrial del Bajío.',
    partnershipFitAngle: 'Canal especializado para conectar con la comunidad de fisioterapia y rehabilitación en clínicas deportivas del Bajío.',
    featuredBadges: ['Ciencias del Deporte', 'Fisioterapia & Biomecánica', 'Corredor Bajío'],
  },

  // MÉRIDA
  {
    id: 'pilates-workcenter-merida',
    slug: 'pilates-workcenter-classic-contrology',
    partnerName: 'Pilates Workcenter (Classic Contrology)',
    city: 'Mérida',
    citySlug: 'merida',
    state: 'Yucatán',
    leadPerson: 'Liliana (Lily) Cruz Guillén / Sean Gallagher (Host)',
    roleTitle: 'Directora Fundadora & Host Internacional',
    website: 'https://pilatesworkcenter.com/',
    email: 'contacto@pilatesworkcenter.com',
    phone: '+52 999 305 3452',
    whatsapp: '+529993053452',
    instagram: 'https://www.instagram.com/pilatesworkcenter/',
    facebook: 'https://www.facebook.com/pilatesworkcenter',
    xTwitter: 'https://twitter.com/pilateswcenter',
    aboutCredentials: 'Pionera del método clásico en Mérida desde 2011. Host oficial de The New York Pilates Studio Teacher Training Program en México impartido con Sean Gallagher. Estudio de máxima fidelidad técnica equipado con aparatos clásicos.',
    certificationsOffered: 'The New York Pilates Studio Teacher Training (Módulos Básico, Intermedio y Avanzado) y workshops de biomecánica funcional aplicada al sistema clásico.',
    studioLocations: 'Calle 61 #252 x 32 y 32A, Depto. 3, San Ramón Norte / Col. García Ginerés, Mérida, Yucatán C.P. 97070.',
    partnershipFitAngle: 'Centro neurálgico de certificación clásica en el sureste y Península de Yucatán. Alumnas de alto nivel adquisitivo y hotelería de lujo en Mérida y Valladolid.',
    featuredBadges: ['The New York Pilates Studio Host', 'Sean Gallagher', 'San Ramón Norte Mérida'],
    isFlagship: true,
  },
];

export function getPartnersByCitySlug(citySlug: string): CertificationPartner[] {
  const normalized = normalizeCitySlug(citySlug);
  return CERTIFICATION_PARTNERS.filter(p => p.citySlug === normalized);
}

export function getCityInfo(citySlug: string): CertificationCity | undefined {
  const normalized = normalizeCitySlug(citySlug);
  return CERTIFICATION_CITIES.find(c => c.key === normalized);
}

export function normalizeCitySlug(slug: string): string {
  const s = (slug || '').toLowerCase().trim();
  if (s === 'ciudad-de-mexico' || s === 'mexico' || s === 'df') return 'cdmx';
  if (s === 'zapopan') return 'guadalajara';
  if (s === 'cancun' || s === 'playa-del-carmen') return 'riviera-maya';
  if (s === 'san-pedro' || s === 'valle-oriente') return 'monterrey';
  return s;
}
